### ISSUE TITLE
Text content did not match. Server: "<span>Browser doesn't support speech recognition.</span>" Client: " "

### ISSUE THREAD

**Issue by andrejarh** [JavaFXpert/talk-with-gpt3#17]
Can't get it working unfortunately. 
I installed node, and everything, Using latest Chrome on Windows 10.

next-gpt3-chatbot@0.1.0 C:\webdev\talk-with-gpt
+-- @chakra-ui/react@2.5.3
+-- @emotion/react@11.10.6
+-- @emotion/styled@11.10.6
+-- aws-sdk@2.1343.0
+-- dotenv@16.0.3
+-- eslint-config-next@12.2.2
+-- eslint@8.19.0
+-- framer-motion@6.5.1
+-- fs@0.0.1-security
+-- google-search-results-nodejs@2.1.0
+-- next@12.2.2
+-- openai@3.2.1
+-- react-dom@18.2.0
+-- react-speech-recognition@3.10.0
+-- react@18.2.0
`-- regenerator-runtime@0.13.11

 **Here is the console error log:**

next-dev.js?3515:24 Warning: Text content did not match. Server: "<span>Browser doesn't support speech recognition.</span>" Client: " "
    at Home (webpack-internal:///./pages/index.js:1040:62)
    at MyApp (webpack-internal:///./pages/_app.js:14:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23199)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:149:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:652:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:774:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
window.console.error @ next-dev.js?3515:24
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js?ac89:86
error @ react-dom.development.js?ac89:60
checkForUnmatchedText @ react-dom.development.js?ac89:9639
didNotMatchHydratedContainerTextInstance @ react-dom.development.js?ac89:11389
prepareToHydrateHostTextInstance @ react-dom.development.js?ac89:12593
completeWork @ react-dom.development.js?ac89:22232
completeUnitOfWork @ react-dom.development.js?ac89:26596
performUnitOfWork @ react-dom.development.js?ac89:26568
workLoopSync @ react-dom.development.js?ac89:26466
renderRootSync @ react-dom.development.js?ac89:26434
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25738
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
next-dev.js?3515:24 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
window.console.error @ next-dev.js?3515:24
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js?ac89:86
error @ react-dom.development.js?ac89:60
errorHydratingContainer @ react-dom.development.js?ac89:11473
recoverFromConcurrentError @ react-dom.development.js?ac89:25846
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25750
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
react-dom.development.js?ac89:9647 Uncaught Error: Text content does not match server-rendered HTML.
    at checkForUnmatchedText (react-dom.development.js?ac89:9647:1)
    at didNotMatchHydratedContainerTextInstance (react-dom.development.js?ac89:11389:1)
    at prepareToHydrateHostTextInstance (react-dom.development.js?ac89:12593:1)
    at completeWork (react-dom.development.js?ac89:22232:1)
    at completeUnitOfWork (react-dom.development.js?ac89:26596:1)
    at performUnitOfWork (react-dom.development.js?ac89:26568:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
checkForUnmatchedText @ react-dom.development.js?ac89:9647
didNotMatchHydratedContainerTextInstance @ react-dom.development.js?ac89:11389
prepareToHydrateHostTextInstance @ react-dom.development.js?ac89:12593
completeWork @ react-dom.development.js?ac89:22232
completeUnitOfWork @ react-dom.development.js?ac89:26596
performUnitOfWork @ react-dom.development.js?ac89:26568
workLoopSync @ react-dom.development.js?ac89:26466
renderRootSync @ react-dom.development.js?ac89:26434
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25738
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
react-dom.development.js?ac89:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js?ac89:12507:1)
    at tryToClaimNextHydratableInstance (react-dom.development.js?ac89:12520:1)
    at updateHostComponent (react-dom.development.js?ac89:19902:1)
    at beginWork (react-dom.development.js?ac89:21618:1)
    at beginWork$1 (react-dom.development.js?ac89:27426:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
throwOnHydrationMismatch @ react-dom.development.js?ac89:12507
tryToClaimNextHydratableInstance @ react-dom.development.js?ac89:12520
updateHostComponent @ react-dom.development.js?ac89:19902
beginWork @ react-dom.development.js?ac89:21618
beginWork$1 @ react-dom.development.js?ac89:27426
performUnitOfWork @ react-dom.development.js?ac89:26557
workLoopSync @ react-dom.development.js?ac89:26466
renderRootSync @ react-dom.development.js?ac89:26434
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25738
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
react-dom.development.js?ac89:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js?ac89:19849:1)
    at beginWork (react-dom.development.js?ac89:21615:1)
    at beginWork$1 (react-dom.development.js?ac89:27426:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at recoverFromConcurrentError (react-dom.development.js?ac89:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25750:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)

**Comment by JavaFXpert** [comment]
Here’s an online variation that I’ve been keeping up to date:https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChainRegards,James (Jim) WeaverOn Mar 26, 2023, at 8:55 AM, andrejarh ***@***.***> wrote:﻿
Can't get it working unfortunately.
I installed node, and everything, Using latest Chrome on Windows 10.
***@***.*** C:\webdev\talk-with-gpt
+-- @***@***.***
+-- @***@***.***
+-- @***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
+-- ***@***.***
`-- ***@***.***
Here is the console error log:
next-dev.js?3515:24 Warning: Text content did not match. Server: "Browser doesn't support speech recognition." Client: " "
at Home (webpack-internal:///./pages/index.js:1040:62)
at MyApp (webpack-internal:///./pages/_app.js:14:27)
at ErrorBoundary ***@***.***/react-dev-overlay/dist/client.js:8:20740)
at ReactDevOverlay ***@***.***/react-dev-overlay/dist/client.js:8:23199)
at Container (webpack-internal:///./node_modules/next/dist/client/index.js:149:9)
at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:652:26)
at Root (webpack-internal:///./node_modules/next/dist/client/index.js:774:27)
See more info here: https://nextjs.org/docs/messages/react-hydration-error
window.console.error @ next-dev.js?3515:24
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js?ac89:86
error @ react-dom.development.js?ac89:60
checkForUnmatchedText @ react-dom.development.js?ac89:9639
didNotMatchHydratedContainerTextInstance @ react-dom.development.js?ac89:11389
prepareToHydrateHostTextInstance @ react-dom.development.js?ac89:12593
completeWork @ react-dom.development.js?ac89:22232
completeUnitOfWork @ react-dom.development.js?ac89:26596
performUnitOfWork @ react-dom.development.js?ac89:26568
workLoopSync @ react-dom.development.js?ac89:26466
renderRootSync @ react-dom.development.js?ac89:26434
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25738
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
next-dev.js?3515:24 Warning: An error occurred during hydration. The server HTML was replaced with client content in .
See more info here: https://nextjs.org/docs/messages/react-hydration-error
window.console.error @ next-dev.js?3515:24
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js?ac89:86
error @ react-dom.development.js?ac89:60
errorHydratingContainer @ react-dom.development.js?ac89:11473
recoverFromConcurrentError @ react-dom.development.js?ac89:25846
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25750
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
react-dom.development.js?ac89:9647 Uncaught Error: Text content does not match server-rendered HTML.
at checkForUnmatchedText (react-dom.development.js?ac89:9647:1)
at didNotMatchHydratedContainerTextInstance (react-dom.development.js?ac89:11389:1)
at prepareToHydrateHostTextInstance (react-dom.development.js?ac89:12593:1)
at completeWork (react-dom.development.js?ac89:22232:1)
at completeUnitOfWork (react-dom.development.js?ac89:26596:1)
at performUnitOfWork (react-dom.development.js?ac89:26568:1)
at workLoopSync (react-dom.development.js?ac89:26466:1)
at renderRootSync (react-dom.development.js?ac89:26434:1)
at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
at workLoop (scheduler.development.js?bcd2:266:1)
at flushWork (scheduler.development.js?bcd2:239:1)
at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
checkForUnmatchedText @ react-dom.development.js?ac89:9647
didNotMatchHydratedContainerTextInstance @ react-dom.development.js?ac89:11389
prepareToHydrateHostTextInstance @ react-dom.development.js?ac89:12593
completeWork @ react-dom.development.js?ac89:22232
completeUnitOfWork @ react-dom.development.js?ac89:26596
performUnitOfWork @ react-dom.development.js?ac89:26568
workLoopSync @ react-dom.development.js?ac89:26466
renderRootSync @ react-dom.development.js?ac89:26434
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25738
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
react-dom.development.js?ac89:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
at throwOnHydrationMismatch (react-dom.development.js?ac89:12507:1)
at tryToClaimNextHydratableInstance (react-dom.development.js?ac89:12520:1)
at updateHostComponent (react-dom.development.js?ac89:19902:1)
at beginWork (react-dom.development.js?ac89:21618:1)
at beginWork$1 (react-dom.development.js?ac89:27426:1)
at performUnitOfWork (react-dom.development.js?ac89:26557:1)
at workLoopSync (react-dom.development.js?ac89:26466:1)
at renderRootSync (react-dom.development.js?ac89:26434:1)
at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
at workLoop (scheduler.development.js?bcd2:266:1)
at flushWork (scheduler.development.js?bcd2:239:1)
at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
throwOnHydrationMismatch @ react-dom.development.js?ac89:12507
tryToClaimNextHydratableInstance @ react-dom.development.js?ac89:12520
updateHostComponent @ react-dom.development.js?ac89:19902
beginWork @ react-dom.development.js?ac89:21618
beginWork$1 @ react-dom.development.js?ac89:27426
performUnitOfWork @ react-dom.development.js?ac89:26557
workLoopSync @ react-dom.development.js?ac89:26466
renderRootSync @ react-dom.development.js?ac89:26434
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25738
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533
react-dom.development.js?ac89:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
at updateHostRoot (react-dom.development.js?ac89:19849:1)
at beginWork (react-dom.development.js?ac89:21615:1)
at beginWork$1 (react-dom.development.js?ac89:27426:1)
at performUnitOfWork (react-dom.development.js?ac89:26557:1)
at workLoopSync (react-dom.development.js?ac89:26466:1)
at renderRootSync (react-dom.development.js?ac89:26434:1)
at recoverFromConcurrentError (react-dom.development.js?ac89:25850:1)
at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25750:1)
at workLoop (scheduler.development.js?bcd2:266:1)
at flushWork (scheduler.development.js?bcd2:239:1)
at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
