### ISSUE TITLE
This is fantastic, just running into issue with want to customize avatar

### ISSUE THREAD

**Issue by SILKWEBAGENCY** [JavaFXpert/talk-with-gpt3#3]
Hi thank you very much for creating this brilliant app. It is working perfectly! Just having a challenge getting in touch with Ex-Human, I want to customize this Avatar and have sent them emails, submitted forms multiple times, no reply yet. Did it take this long for you to get a reply back from them? Any other ideas for customization?

**Comment by stevenbaert** [comment]
It takes some time before you get response. For me it took even few days but finally received the key. Though adding the key didn't make the avatar work for me. Just that you know.

**Comment by JavaFXpert** [comment]
To confirm, the avatars aren’t working? Regards,James (Jim) WeaverOn Sep 23, 2022, at 4:54 PM, stevenbaert ***@***.***> wrote:﻿
It takes some time before you get response. For me it took even few days but finally received the key. Though adding the key didn't make the avatar work for me. Just that you know.

**Comment by stevenbaert** [comment]
Thanks for your feedback. Not yet, might be api key, not your code.
Received the api key this morning. Not sure how I can verify/troubleshoot
that it is/isn't working.

Was planning to download your new code (with web checks for recent,
awesome!) and start fresh since I did quite some changes but haven't found
the time yet...

Op za 24 sep. 2022 00:35 schreef James Weaver ***@***.***>:

**Comment by JavaFXpert** [comment]
Cool. Thanks. The web checks are pretty alpha, so hope you like it as well as the version you’ve been using.Regards,James (Jim) WeaverOn Sep 23, 2022, at 6:49 PM, stevenbaert ***@***.***> wrote:﻿
Thanks for your feedback. Not yet, might be api key, not your code.
Received the api key this morning. Not sure how I can verify/troubleshoot
that it is/isn't working.

Was planning to download your new code (with web checks for recent,
awesome!) and start fresh since I did quite some changes but haven't found
the time yet...

Op za 24 sep. 2022 00:35 schreef James Weaver ***@***.***>:

**Comment by stevenbaert** [comment]
Finally found some time to test new version. Looks nice, but not sure if
web works as expected.
Key is correctly activated for Serpapi, since I had the error no key was
entered first time I asked something. When I entered the key, the errors
are gone. Example below
*--- error without key - now gone*
*Question:*
*req.body.question:How old is Elon Musk?*
*Error: api_key is required. copy it from: https://serpapi.com/dashboard
<https://serpapi.com/dashboard>*
*    at GoogleSearch.buildUrl (C:\Users\steven\OneDrive -
Telenet\GPT-3\talk-with-gpt3-Web\node_modules\google-search-results-nodejs\lib\SerpApiSearch.js:41:15)*
*---*

Why I assume there is something not fully working => the answer to "how old
is Musk" was 48, Barack Obama 59 years and "there is no war in Ukraine, to
the particular question".

Then tried your example:
Elon Musk is the founder of Tesla.
Human: how old is he
Matthew:

Elon Musk is 48 years old.

Maybe I should test it differently?


*Notes: *

- I would love it if you could make a stripped down version of the code, or
get some code blocks in another script so I better understand the core code
to edit and help you (that's the idea, to help you adding features, when I
get a hang of NodeJs) => see issues logged by me
-would love to see some logging to understand better what is going on (like
the error on
-when I switch a voice, I have to put it to sleep then wake up before it
works again (small bug)
-error I saw in dev mode Chrome for Lipsync (your latest version of code,
no changes done):
Uncaught Error: Minified React error #418; visit
https://reactjs.org/docs/error-decoder.html?invariant=418 for the full
message or use the non-minified dev environment for full errors and
additional helpful warnings.
    at e8 (framework-a03b250610f032e5.js:11:47258)
    at _ (framework-a03b250610f032e5.js:11:121606)
    at ii (framework-a03b250610f032e5.js:11:107942)
    at ig (framework-a03b250610f032e5.js:11:107870)
    at ie (framework-a03b250610f032e5.js:11:107732)
    at h3 (framework-a03b250610f032e5.js:11:102837)
    at A (framework-a03b250610f032e5.js:35:1374)
    at MessagePort.g (framework-a03b250610f032e5.js:35:1906)
framework-a03b250610f032e5.js:11 Uncaught Error: Minified React error #423;
visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the
full message or use the non-minified dev environment for full errors and
additional helpful warnings.
    at _ (framework-a03b250610f032e5.js:11:121268)
    at ii (framework-a03b250610f032e5.js:11:107942)
    at ig (framework-a03b250610f032e5.js:11:107870)
    at ie (framework-a03b250610f032e5.js:11:107732)
    at h4 (framework-a03b250610f032e5.js:11:104100)
    at h3 (framework-a03b250610f032e5.js:11:103065)
    at A (framework-a03b250610f032e5.js:35:1374)
    at MessagePort.g (framework-a03b250610f032e5.js:35:1906)
DevTools failed to load source map: Could not load content for
chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map:
System error: net::ERR_FILE_NOT_FOUND
VM17:1          POST https://api.exh.ai/animations/v1/generate_lipsync
net::ERR_CONNECTION_RESET
(anonymous) @ VM17:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
a6 @ index-c00ecbf53e81b2f5.js:1
a5 @ index-c00ecbf53e81b2f5.js:1
aN @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
Promise.then (async)
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
Promise.then (async)
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
bc @ index-c00ecbf53e81b2f5.js:1
bb @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
a8 @ index-c00ecbf53e81b2f5.js:1
a7 @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
he @ framework-a03b250610f032e5.js:11
im @ framework-a03b250610f032e5.js:11
(anonymous) @ framework-a03b250610f032e5.js:11
A @ framework-a03b250610f032e5.js:35
g @ framework-a03b250610f032e5.js:35
index-c00ecbf53e81b2f5.js:1 Problem w/video?
:TypeError: Failed to fetch

VM17:1          POST https://api.exh.ai/animations/v1/generate_lipsync
net::ERR_CONNECTION_RESET
(anonymous) @ VM17:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
a6 @ index-c00ecbf53e81b2f5.js:1
a5 @ index-c00ecbf53e81b2f5.js:1
aN @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
Promise.then (async)
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
Promise.then (async)
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
bc @ index-c00ecbf53e81b2f5.js:1
bb @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
a8 @ index-c00ecbf53e81b2f5.js:1
a7 @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
he @ framework-a03b250610f032e5.js:11
im @ framework-a03b250610f032e5.js:11
(anonymous) @ framework-a03b250610f032e5.js:11
A @ framework-a03b250610f032e5.js:35
g @ framework-a03b250610f032e5.js:35
index-c00ecbf53e81b2f5.js:1 Problem w/video?
:TypeError: Failed to fetch
VM17:1          POST https://api.exh.ai/animations/v1/generate_lipsync
net::ERR_CONNECTION_RESET
(anonymous) @ VM17:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
a6 @ index-c00ecbf53e81b2f5.js:1
a5 @ index-c00ecbf53e81b2f5.js:1
aN @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
Promise.then (async)
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
Promise.then (async)
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
bc @ index-c00ecbf53e81b2f5.js:1
bb @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
u @ main-e30ba8f4087d3abf.js:1
(anonymous) @ main-e30ba8f4087d3abf.js:1
a.<computed> @ main-e30ba8f4087d3abf.js:1
d @ 59-11006a585cff877e.js:6
e @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
(anonymous) @ 59-11006a585cff877e.js:6
a8 @ index-c00ecbf53e81b2f5.js:1
a7 @ index-c00ecbf53e81b2f5.js:1
(anonymous) @ index-c00ecbf53e81b2f5.js:1
he @ framework-a03b250610f032e5.js:11
im @ framework-a03b250610f032e5.js:11
(anonymous) @ framework-a03b250610f032e5.js:11
A @ framework-a03b250610f032e5.js:35
g @ framework-a03b250610f032e5.js:35
index-c00ecbf53e81b2f5.js:1 Problem w/video?
:TypeError: Failed to fetch


Again, love this project and appreciate your efforts!

All the best!

Kind regards,
Steven

**Comment by stevenbaert** [comment]
! Update to last mail: did a rebuild just to be sure.
I see connection to Serpapi now, but it hangs :-(

Log below (not continuing after "Calling querySerpapi")

index-7eee1eb6e32ab768.js:1 intentArg:Elon Musk
index-7eee1eb6e32ab768.js:1 intentRequest: how old is Elon Musk
index-7eee1eb6e32ab768.js:1 COMPLETE QUESTION:How old is Elon Musk?
index-7eee1eb6e32ab768.js:1 ===Conversation so far: Human: how old is Elon
Musk

index-7eee1eb6e32ab768.js:1 ===Question from conversation: How old is Elon
Musk?
index-7eee1eb6e32ab768.js:1 ===Intent: AskAgeIntent
index-7eee1eb6e32ab768.js:1 cleanedIntentReq.toLowerCase():how old is elon
musk
index-7eee1eb6e32ab768.js:1 intentRequest: How old is Elon Musk?
index-7eee1eb6e32ab768.js:1 $$$$$Temporal string:
index-7eee1eb6e32ab768.js:1 *Calling querySerpapi*

**Comment by stevenbaert** [comment]
Update on this sepapi topic:

timeout Serpapi "DevTools failed to load source map: Could not load content
for
chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map:
System error: net::ERR_FILE_NOT_FOUND"
found this and looking into it [extension] DevTools failed to load
SourceMap: Could not load content for browser-polyfill.js.map · Issue #1977
· dequelabs/axe-core · GitHub
<https://github.com/dequelabs/axe-core/issues/1977>

**Comment by stevenbaert** [comment]
fyi: no luck, had some tries with extensions in chrome, set security to off
etc but result is still the same for serpapi.

**Comment by JavaFXpert** [comment]
It doesn’t seem like the SerpApi key is working. When you first start the application, try “who is currently the King of England”. It should respond, of course, with something including King Charles III.Regards,James (Jim) WeaverOn Sep 24, 2022, at 10:34 AM, stevenbaert ***@***.***> wrote:﻿
Update on this sepapi topic:

timeout Serpapi "DevTools failed to load source map: Could not load content
for
chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map:
System error: net::ERR_FILE_NOT_FOUND"
found this and looking into it [extension] DevTools failed to load
SourceMap: Could not load content for browser-polyfill.js.map · Issue #1977
· dequelabs/axe-core · GitHub
<https://github.com/dequelabs/axe-core/issues/1977>

**Comment by JavaFXpert** [comment]
Perhaps you’ll want to try on an environment closer to what I’ve test on: Mac w/Chrome, and Windows w/Chrome. The polyfill in the error message opens up all sorts of possibilities as to what could be going wrong.If you have access to an inexpensive windows tablet such a Surface Go (with a keyboard), that would be an environment closer to what I’ve tested on. It is also something you could carry around easily, which is a desire that I think you’ve ecpressed.Regards,James (Jim) WeaverOn Sep 24, 2022, at 11:21 AM, James Weaver ***@***.***> wrote:﻿
It doesn’t seem like the SerpApi key is working. When you first start the application, try “who is currently the King of England”. It should respond, of course, with something including King Charles III.Regards,James (Jim) WeaverOn Sep 24, 2022, at 10:34 AM, stevenbaert ***@***.***> wrote:﻿
Update on this sepapi topic:

timeout Serpapi "DevTools failed to load source map: Could not load content
for
chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map:
System error: net::ERR_FILE_NOT_FOUND"
found this and looking into it [extension] DevTools failed to load
SourceMap: Could not load content for browser-polyfill.js.map · Issue #1977
· dequelabs/axe-core · GitHub
<https://github.com/dequelabs/axe-core/issues/1977>

**Comment by stevenbaert** [comment]
Thanks James, it is running on a portable Windows and on a Synology NAS.
For both I have the same issue with Google Chrome.
I could try on a Mac, but you have also the Windows setup, so that should
work.

I carry it around via Chrome on my Android phone ssl vpn. Though when
Chrome closed on Android, the microphone is disabled/doesn't listen
anymore. Haven't found a way to enable that (once Chrome is minimized).

Kind regards,
Steven Baert

Op za 24 sep. 2022 17:31 schreef James Weaver ***@***.***>:

> Perhaps you’ll want to try on an environment closer to what I’ve test on:
> Mac w/Chrome, and Windows w/Chrome. The polyfill in the error message opens
> up all sorts of possibilities as to what could be going wrong.If you have
> access to an inexpensive windows tablet such a Surface Go (with a
> keyboard), that would be an environment closer to what I’ve tested on. It
> is also something you could carry around easily, which is a desire that I
> think you’ve ecpressed.Regards,James (Jim) WeaverOn Sep 24, 2022, at 11:21
> AM, James Weaver ***@***.***> wrote:﻿
> It doesn’t seem like the SerpApi key is working. When you first start the
> application, try “who is currently the King of England”. It should respond,
> of course, with something including King Charles III.Regards,James (Jim)
> WeaverOn Sep 24, 2022, at 10:34 AM, stevenbaert ***@***.***> wrote:﻿
> Update on this sepapi topic:
>
> timeout Serpapi "DevTools failed to load source map: Could not load content
> for
>
> chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map:
> System error: net::ERR_FILE_NOT_FOUND"
> found this and looking into it [extension] DevTools failed to load
> SourceMap: Could not load content for browser-polyfill.js.map · Issue #1977
> · dequelabs/axe-core · GitHub
> <https://github.com/dequelabs/axe-core/issues/1977>
>
>
